all:
  vars:
    ansible_connection: community.general.incus
    ansible_user: root
    ansible_become: no
  children:
    local:
      vars:
        ansible_incus_remote: local
        ansible_incus_project: dist-logger
      hosts:
        n0:
        n1:
        n2:
        n3:
        n4:
        n5:
        n6:
        n7:
        n8:
        n9:
