- name: Setup nodes
  hosts: all
  tasks:
    - name: Send dist-logger executable to nodes
      ansible.builtin.copy:
        src: "../target/release/dist-logger"
        dest: "/root/"
        mode: '755'

    - name: Copy topology
      ansible.builtin.copy:
        src: "topologies/{{ topology }}.json"
        dest: "/root/topology.json"

    - name: Run dist-logger
      ansible.builtin.command: /root/dist-logger
