- name: Setup nodes
  hosts: all
  vars:
    topology: "fully_connected" # Provide a default value or ensure it's defined elsewhere
  tasks:
    - name: Copy topology JSON
      ansible.builtin.copy:
        src: "topologies/{{ topology }}.json"
        dest: "/root/topology.json"
      tags: always
    - name: Deploy and run binaries (debug)
      block:
        - name: Copy executables (debug)
          ansible.builtin.copy:
            src: "../target/debug/dl-{{ item }}"
            dest: /root/
            mode: '0755'
          loop:
            - server
            - client
        - name: Run executables (debug)
          ansible.builtin.command: "/root/dl-{{ item }}"
          loop:
            - server
            - client
      tags: debug
    - name: Deploy and run binaries (release)
      block:
        - name: Copy executables (release)
          ansible.builtin.copy:
            src: "../target/release/dl-{{ item }}"
            dest: /root/
            mode: '0755'
          loop:
            - server
            - client
        - name: Run executables (release)
          ansible.builtin.command: "/root/dl-{{ item }}"
          loop:
            - server
            - client
      tags: release
