- name: Setup nodes
  hosts: all
  vars:
    topology: "fully_connected" # Provide a default value or ensure it's defined elsewhere
  tasks:
    - name: Copy topology JSON
      ansible.builtin.copy:
        src: "topologies/{{ topology }}.json"
        dest: "/root/topology.json"
      tags: always
    - name: Copy binaries (debug)
      ansible.builtin.copy:
        src: "../target/debug/dl-{{ item }}"
        dest: /root/
        mode: '0755'
      loop:
        - server
        - client
      tags: debug
    - name: Copy binariess (release)
      ansible.builtin.copy:
        src: "../target/release/dl-{{ item }}"
        dest: /root/
        mode: '0755'
      loop:
        - server
        - client
      tags: release
    - name: Copy service files
      ansible.builtin.copy:
        src: "./services/dl{{ item }}.service"
        dest: /etc/systemd/system/
        mode: '0644'
      loop:
        - server
        - client
      tags: always
    - name: Reload systemd daemon
      ansible.builtin.command: systemctl daemon-reload
    - name: Enable and stract services
      ansible.builtin.systemd:
        name: "dl{{ item }}.service"
        enabled: yes
        state: started
      loop:
        - server
        - client
      tags: always
